import jsPDF from 'jspdf';

export const generateSamplePDF = () => {
  const doc = new jsPDF();
  
  // Add PlagLab logo/header
  doc.setFontSize(24);
  doc.setTextColor(63, 81, 181); // Primary blue color
  doc.text('PlagLab', 105, 20, { align: 'center' });
  
  doc.setFontSize(18);
  doc.setTextColor(33, 33, 33);
  doc.text('AI Content Detection Report', 105, 35, { align: 'center' });
  
  // Document info
  doc.setFontSize(12);
  doc.setTextColor(89, 89, 89);
  doc.text('Document ID: AI-2025-04-19-1234', 20, 50);
  doc.text('Submission Date: April 19, 2025', 20, 60);
  doc.text('Word Count: 1,567 words', 20, 70);
  
  // AI Detection Results
  doc.setFontSize(16);
  doc.setTextColor(33, 33, 33);
  doc.text('AI Detection Results', 20, 90);
  
  doc.setFontSize(12);
  doc.setTextColor(89, 89, 89);
  doc.text('Overall AI Probability: 87%', 30, 105);
  doc.text('Confidence Level: High', 30, 115);
  doc.text('Detected AI Models: GPT-4, Claude', 30, 125);
  
  // Section Analysis
  doc.setFontSize(16);
  doc.setTextColor(33, 33, 33);
  doc.text('Content Analysis by Section', 20, 145);
  
  doc.setFontSize(12);
  doc.setTextColor(89, 89, 89);
  doc.text('Introduction: 92% AI', 30, 160);
  doc.text('Literature Review: 95% AI', 30, 170);
  doc.text('Methodology: 76% AI', 30, 180);
  doc.text('Conclusion: 32% AI', 30, 190);
  
  // Recommendation
  doc.setFontSize(16);
  doc.setTextColor(33, 33, 33);
  doc.text('Recommendation', 20, 210);
  
  doc.setFontSize(12);
  doc.setTextColor(89, 89, 89);
  const recommendation = 'Based on our analysis, this document shows strong indicators of being primarily AI-generated with minimal human editing. We recommend requesting a complete rewrite with authentic human input.';
  doc.text(doc.splitTextToSize(recommendation, 170), 20, 225);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by PlagLab - www.plaglab.com', 105, 280, { align: 'center' });
  
  // Save the PDF
  return doc.save('public/samples/sample-ai-report.pdf');
};