
import Layout from "@/components/layout/Layout";

const Terms = () => {
  return (
    <Layout>
      <div className="py-12 px-4 md:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="mb-12">
            <h1 className="text-4xl font-bold mb-4">Terms and Conditions</h1>
            <p className="text-gray-600">Last updated: April 19, 2025</p>
          </div>

          <div className="prose prose-lg max-w-none">
            <p>
              Welcome to PlagLab. These Terms and Conditions ("Terms") govern your use of our website and services for plagiarism and AI content detection (collectively, "Services"). By accessing or using our Services, you agree to be bound by these Terms. If you disagree with any part of these Terms, you may not access the Services.
            </p>

            <h2>1. Use of Services</h2>
            <p>
              <strong>1.1 Account Registration.</strong> To use certain features of our Services, you may need to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
            </p>
            <p>
              <strong>1.2 Account Security.</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
            </p>
            <p>
              <strong>1.3 Acceptable Use.</strong> You agree to use our Services only for lawful purposes and in accordance with these Terms. You agree not to:
            </p>
            <ul>
              <li>Use the Services in any way that violates any applicable law or regulation</li>
              <li>Attempt to interfere with, compromise the system integrity or security, or decipher any transmissions to or from the servers running the Services</li>
              <li>Use any robot, spider, or other automatic device to access the Services for any purpose without our express written permission</li>
              <li>Upload or transmit viruses, malware, or any other code of a destructive nature</li>
              <li>Impersonate or attempt to impersonate ContentShield, a ContentShield employee, another user, or any other person or entity</li>
              <li>Collect or track the personal information of others</li>
            </ul>

            <h2>2. Service Description</h2>
            <p>
              <strong>2.1 Plagiarism Detection.</strong> Our plagiarism detection service compares submitted content against a database of web pages, academic papers, publications, and other sources to identify potential matches or similarities. The service provides a report indicating the likelihood of plagiarism and potential matching sources.
            </p>
            <p>
              <strong>2.2 AI Content Detection.</strong> Our AI content detection service analyzes submitted content using various algorithms and techniques to determine the probability that the content was generated by artificial intelligence tools rather than written by a human.
            </p>
            <p>
              <strong>2.3 Accuracy and Limitations.</strong> While we strive to provide accurate and reliable results, no detection system is perfect. Our Services provide probabilistic assessments and should be used as tools to assist in content evaluation, not as definitive determinations of plagiarism or AI generation. You acknowledge that false positives and false negatives may occur.
            </p>

            <h2>3. Content</h2>
            <p>
              <strong>3.1 Your Content.</strong> When you upload or submit content to our Services for analysis, you retain all ownership rights to your content. By submitting content, you grant us a limited license to use, process, and store your content solely for the purpose of providing our Services to you.
            </p>
            <p>
              <strong>3.2 Data Retention.</strong> By default, we do not store the full text of your submitted content after analysis is complete. We may retain certain metadata about your submissions for service improvement and account history purposes. Please refer to our Privacy Policy for more information on how we handle your data.
            </p>
            <p>
              <strong>3.3 Prohibited Content.</strong> You agree not to submit content that:
            </p>
            <ul>
              <li>Is illegal, harmful, threatening, abusive, harassing, defamatory, obscene, or otherwise objectionable</li>
              <li>Infringes on any patent, trademark, trade secret, copyright, or other intellectual property rights</li>
              <li>Contains software viruses or any other code designed to interrupt, destroy, or limit the functionality of computer software or hardware</li>
              <li>Contains personal, confidential, or sensitive information of others without proper authorization</li>
            </ul>

            <h2>4. Payments and Billing</h2>
            <p>
              <strong>4.1 Pricing.</strong> Pricing for our Services is as specified on our website at the time of purchase. We reserve the right to change our prices at any time, with or without notice.
            </p>
            <p>
              <strong>4.2 Payment Processing.</strong> Payments are processed through secure third-party payment processors. By providing payment information, you represent and warrant that you are authorized to use the payment method and agree to the terms and conditions of the payment processor.
            </p>
            <p>
              <strong>4.3 Refunds.</strong> Our refund policy is outlined in our separate Refund Policy document, which is incorporated into these Terms by reference.
            </p>

            <h2>5. Intellectual Property</h2>
            <p>
              <strong>5.1 Our Content.</strong> The Services and their original content (excluding your submitted content), features, and functionality are and will remain the exclusive property of ContentShield and its licensors. The Services are protected by copyright, trademark, and other intellectual property laws.
            </p>
            <p>
              <strong>5.2 Feedback.</strong> If you provide us with any feedback or suggestions regarding our Services, you assign to us all rights in such feedback and agree that we shall have the right to use such feedback and related information in any manner we deem appropriate without attribution or compensation to you.
            </p>

            <h2>6. Disclaimers</h2>
            <p>
              <strong>6.1 "AS IS" Basis.</strong> The Services are provided on an "AS IS" and "AS AVAILABLE" basis. ContentShield expressly disclaims all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
            <p>
              <strong>6.2 No Guarantees.</strong> ContentShield makes no warranty that the Services will meet your requirements, be available on an uninterrupted, secure, or error-free basis, or that the results obtained from the use of the Services will be accurate or reliable.
            </p>

            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, ContentShield and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Services; (ii) any conduct or content of any third party on the Services; (iii) any content obtained from the Services; or (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.
            </p>

            <h2>8. Termination</h2>
            <p>
              <strong>8.1 Your Right to Terminate.</strong> You may terminate your account at any time by contacting us or using any account deletion features we provide.
            </p>
            <p>
              <strong>8.2 Our Right to Terminate.</strong> We may terminate or suspend your account and access to the Services immediately, without prior notice or liability, for any reason, including but not limited to a breach of these Terms.
            </p>
            <p>
              <strong>8.3 Effect of Termination.</strong> Upon termination, your right to use the Services will immediately cease. If your account is terminated due to your breach of these Terms, you may not register a new account without our permission.
            </p>

            <h2>9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of significant changes by updating the "Last updated" date at the top of these Terms and/or by other means as determined by us. Your continued use of the Services after such changes constitutes your acceptance of the new Terms.
            </p>

            <h2>10. Governing Law and Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Bengaluru, India.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us:
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;
